### ISSUE TITLE
Can't send big text data

### ISSUE THREAD

**Issue by LunevNF** [arissa34/Android-Bluetooth-Library#4]
Hello. Why I can't send a text with length more than 1024 symbols?
I always get this error and can't fix it:

>  FATAL EXCEPTION: Thread-6620
                                                                java.lang.ArrayIndexOutOfBoundsException: length=1024; index=1024
                                                                    at com.ramimartin.bluetooth.BluetoothClient.run(BluetoothClient.java:83)
                                                                    at java.lang.Thread.run(Thread.java:841)

I already try to send blocks of big text and concatenate after getting full text, but I send very fast and, as I understand, client gets concatenated text (part11 + part12 for example).

What me must do to resolve this issue?
I need your help :(

**Comment by arissa34** [comment]
Hello,
In the lib, on [BluetoothServer.class](https://github.com/arissa34/Android-Bluetooth-Library/blob/master/Bluetooth/Bluetooth_lib/src/main/java/com/ramimartin/bluetooth/BluetoothServer.java) I use a bufferSize at 1024. I suggest you to change this value.

**Comment by arissa34** [comment]
Hello,
In the lib, on [BluetoothService.class](https://github.com/arissa34/Android-Bluetooth-Library/blob/master/Bluetooth/Bluetooth_lib/src/main/java/com/ramimartin/bluetooth/BluetoothServer.java) I use a buffer Size at 1024. I suggest you to change this value.

**Comment by LunevNF** [comment]
Thanks, I already do it, but I found more mistakes at code. I was clone your project, update it and will fork library (multi-clients library) with changes. Thank you, good lib:)
